org: kranous05

app: newstore-auth-manager
service: newstore-authentication

package: 
  individually: true
  patterns:
    - '!tests/**'
    - '!package.json'
    - '!package-lock.json'
    - '!node_modules/**'
    - '!utils/**'
  
#frameworkVersion: '3'

plugins:
  - serverless-python-requirements


provider:
  name: aws
  stage: dev
  region: us-east-1
  stackName: newstore-auth-manager
  deploymentMethod: direct
  runtime: python3.9
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 
            - dynamodb:GetItem
            - dynamodb:PutItem
          Resource: { "Fn::GetAtt": ["TokenCacheTable", "Arn"]}
        - Effect: Allow
          Action: 
            - ssm:GetParameters
            - ssm:GetParameter
            - ssm:GetParametersByPath
          Resource: arn:aws:ssm:${self:provider.region}:*:parameter/newstore/creds/*
  

functions:
  newstore-credential-manager:
    name: newstore-credential-manager
    handler: newstore_auth_manager.aws.handlers.newstore_credential_manager.handler
    memorySize: 128
    timeout: 30
    package:
      patterns:
        - '!aws/handlers/newstore_credential_manager.py'
        - '!aws/utils/**'
    environment:
      TENANT: ccx-sandbox
      LOG_LEVEL: INFO

resources:
  Resources:
    TokenCacheTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: newstore-token-cache
        AttributeDefinitions:
          - AttributeName: key
            AttributeType: S
        KeySchema:
          - AttributeName: key
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TimeToLiveSpecification:
          AttributeName: cache_ttl
          Enabled: true     