service: newstore-auth-manager

plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters

custom:
  pythonRequirements:
    dockerizePip: false

package:
  exclude:
    - ./**
  include:
    - newstore_auth_manager/**

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'x'}
  tenant: faherty
  region: us-east-1
  deploymentBucket: ${self:provider.tenant}-${self:provider.stage}-0-newstore-dmz-deploy
  configBucket: ${self:provider.tenant}-${self:provider.stage}-0-newstore-dmz
  role: arn:aws:iam::#{AWS::AccountId}:role/LambdaExecutionRole
  environment:
    STAGE: ${self:provider.stage}
    TENANT: ${self:provider.tenant}
  apiGateway:
    apiKeys:
      - ${self:provider.stage}-ns-creds-key

functions: 
  newstore_credential_manager:
    name: ${self:provider.tenant}-newstore-credential-manager
    handler: newstore_auth_manager.aws.handlers.newstore_credential_manager.handler
    timeout: 300
    memorySize: 128
    environment:
      TENANT: ${self:provider.tenant}
      LOG_LEVEL: INFO
  add_newstore_credentials:
    name: ${self:provider.tenant}-add-newstore-credential
    handler: newstore_auth_manager.aws.handlers.add_newstore_credential.handler
    timeout: 300
    memorySize: 128
    environment:
      TENANT: ${self:provider.tenant}
      LOG_LEVEL: INFO

resources:
  Resources:
    TokenCacheTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: newstore-token-cache
        AttributeDefinitions:
          - AttributeName: key
            AttributeType: S
        KeySchema:
          - AttributeName: key
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TimeToLiveSpecification:
          AttributeName: cache_ttl
          Enabled: true